env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]